### ISSUE TITLE
Venue Page - Green Bubbles don't work as expected

### ISSUE THREAD

**Issue by shawnidanner** [infinitered/ChainReactApp2019#193]
They either take multiple taps to open purple box, but box doesn't stay open so you can even tell what it says.

**Comment by shawnidanner** [comment]
why are some green bubbles different shapes?

**Comment by shawnidanner** [comment]
Is it supposed to show bubbles of which tab you're under? IE) If I'm on the drink tab, I expect to see brewery. If I'm under Sights tab, I don't expect to see food bubbles.

**Comment by robinheinze** [comment]
I think the bubbles are different if the place is a "Sight" vs. food/drink/hotel. @justinhuskey might be able to confirm, since I think that's part of the custom MapBox style URL: `mapbox://styles/jhuskey/cjabpqolp3lf02so534xe4q9g`

The map does not change when you switch tabs. It just shows all points all the time. 

I think the multiple taps might be because the touchable area is too small. I can try to increase that.
